# 切片

# 一维数组的切片
## 前置配置

In [2]:
# -*-coding:utf-8-*-
import numpy as np
_Number = 100
# 生成 [0~99]
Arrays = np.arange(0,_Number)

## 操作

In [3]:
print(Arrays[1:5])
# 切片 Arrays[1] - Arrays[4]

[1 2 3 4]


In [4]:
print(Arrays[:5])
# 切片 Arrays[0] - Arrays[4]

[0 1 2 3 4]


In [5]:
print(Arrays[:50:5])
# [0~50) 每隔 5 抽取一个
print(Arrays[1::5])
# [1~_Number) 每隔 5 抽取一个
print(Arrays[10:90:2])
# [10~90) 每隔 2 抽取一个

[ 0  5 10 15 20 25 30 35 40 45]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]
